const $=s=>document.querySelector(s); let root=null, current=null, files=new Map(), tabs=[]; const extLang={js:'JavaScript',mjs:'JavaScript',ts:'TypeScript',py:'Python',c:'C',h:'C/C++ Header',cpp:'C++',java:'Java',go:'Go',rs:'Rust',html:'HTML',css:'CSS',json:'JSON',md:'Markdown',sh:'Shell'};
function language(p){return extLang[(p.split('.').pop()||'').toLowerCase()]||'Plain Text'}
function lines(){const n=$('#editor').value.split('\n').length;$('#gutter').textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}
function renderTree(){const t=$('#tree');t.innerHTML='';if(!root){t.innerHTML='<div class="empty">Open a folder to explore files.</div>';return} function walk(dir,level){for(const e of files.get(dir)||[]){const d=document.createElement('div');d.className='node '+(e.directory?'folder':'file');d.style.paddingLeft=(6+level*16)+'px';d.textContent=(e.directory?'▾ ':'')+e.name;d.onclick=async()=>{if(e.directory){await loadDir(e.path);renderTree()}else openFile(e.path)};t.appendChild(d)}} walk(root,0)}
async function loadDir(dir){files.set(dir,await window.ide.list(dir));for(const e of files.get(dir)){if(e.directory&&!e.name.startsWith('.')) files.set(e.path,await window.ide.list(e.path))}}
async function openFile(p){if(!files.has(p))return; if(!tabs.includes(p))tabs.push(p);current=p;$('#editor').value=await window.ide.readFile(p);$('#language').textContent=language(p);renderTabs();lines();$('#status').textContent=p}
function renderTabs(){const x=$('#tabs');x.innerHTML='';tabs.forEach(p=>{const d=document.createElement('div');d.className='tab '+(p===current?'active':'');d.innerHTML=p.split(/[\\/]/).pop()+' <span class="close">×</span>';d.onclick=e=>e.target.className==='close'?closeTab(p):openFile(p);x.appendChild(d)})}
function closeTab(p){tabs=tabs.filter(x=>x!==p);if(current===p)current=tabs[tabs.length-1];current?openFile(current):($('#editor').value='',$('#language').textContent='Plain Text');renderTabs()}
async function save(){if(current){await window.ide.writeFile(current,$('#editor').value);$('#status').textContent='Saved '+current;await loadDir(root);renderTree()}}
function output(s,err=false){const o=$('#output');o.textContent+=s;o.scrollTop=o.scrollHeight}
function command(cmd){if(!root)return output('Open a folder first.\n',true);const id=Date.now();window.ide.start(id,root,cmd);window.ide.onOutput((i,s,type)=>{if(i===id)output(s,type==='stderr')});window.ide.onExit((i,c)=>{if(i===id)output(`\n[process exited with code ${c}]\n`)});return id}
function run(){if(!current)return output('Open a source file first.\n',true);save();const ext=current.split('.').pop().toLowerCase(), rel=current.slice(root.length+1), cmds={js:`node "${rel}"`,mjs:`node "${rel}"`,py:`python "${rel}"`,c:`gcc "${rel}" -o .myide-out && ./.myide-out`,cpp:`g++ "${rel}" -o .myide-out && ./.myide-out`,go:`go run "${rel}"`,java:`javac "${rel}" && java "${rel.replace(/\\.java$/,'')}"`};command(cmds[ext]||`echo "No run configuration for ${ext||'this file'}"`)}
$('#openFolder').onclick=async()=>{root=await window.ide.openFolder();if(root){files.clear();await loadDir(root);$('#projectName').textContent=root;renderTree();$('#status').textContent='Workspace ready'}};$('#save').onclick=save;$('#run').onclick=run;$('#stop').onclick=()=>output('\nStop is available per active process from the terminal.\n');$('#editor').oninput=lines;$('#editor').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const a=e.target.selectionStart;e.target.setRangeText('  ',a,e.target.selectionEnd,'end');lines()}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();save()}};$('#command').onkeydown=e=>{if(e.key==='Enter'){const c=e.target.value;e.target.value='';output('$ '+c+'\n');command(c)}};$('#newFile').onclick=async()=>{if(root){const n=prompt('File name');if(n){const p=await window.ide.writeFile(root+'/'+n,'');await loadDir(root);renderTree();openFile(root+'/'+n)}}};$('#newFolder').onclick=async()=>{if(root){const n=prompt('Folder name');if(n){await window.ide.mkdir(root,n);await loadDir(root);renderTree()}}};document.querySelectorAll('.bottom-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pane').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.pane).classList.remove('hidden')});renderTree();lines();
